drfik/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('main.urls', namespace='main'),),
]

main/urls.py
from django.conf.urls import url, include
from main import views

urlpatterns = [
    url(
        r'^register/',
        views.RegisterUserView.as_view(),
        name='register_user'
    ),
    url(
        r'^login/',
        views.LoginUserView.as_view(),
        name='login_user'
    ),
    url(
        r'^logout/',
        views.LogoutUserView.as_view(),
        name='logout_user'
    ),
    url(
        r'^forgot_password/',
        views.ForgotPasswordView.as_view(),
        name='forgot_password'
    ),
    url(
        r'^set_password/',
        views.SetPasswordView.as_view(),
        name='set_password'
    ),
    url(
        r'^create_team/',
        views.CreateTeamView.as_view(),
        name='create_team'
    ),
    url(
        r'^invite/',
        views.InviteView.as_view(),
        name='invite'
    ),
    url(
        r'^(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        include([
                url(
                    r'^confirm/$',
                    views.ConfirmView.as_view(),
                    name='confirm'
                ),
                url(
                    r'^forgot_password_accept/$',
                    views.ForgotPasswordAccept.as_view(),
                    name='forgot_password_accept'
                ),
            ])
    ),



]

templates/confirmation_email.html
{% autoescape off %}
Confirm your email
http://{{ site }}{% url 'main:confirm' uidb64=uid token=token %}
{% endautoescape %}

templates/forgot_password.html
{% autoescape off %}
Confirm forgot password
http://{{ site }}{% url 'main:forgot_password_accept' uidb64=uid token=token %}
{% endautoescape %}

templates/invite_email.html
{% autoescape off %}
User {{ username }} invite you
http://{{ site }}{% url 'main:register_user' %}/?team={{ team }}
{% endautoescape %}